version: "3.8"

services:
#  app:
#    build:
#      context: .
#      dockerfile: docker/dev/web/Dockerfile
#    ports:
#      - "8021:8000"
#    depends_on:
#      - db
#    restart: unless-stopped
  db:
    image: postgres:13
    env_file:
      - docker/dev/env/.db.env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    restart: always
